<?php

use Illuminate\Database\Seeder;

class Catalogo_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('catalogo')->insert([
            ['nombre'=>'TIPO_ACTIVIDAD','descripcion'=>'TIPO DE ACTIVIDAD'],
            ['nombre'=>'TIPO_DOCUMENTO','descripcion'=>'TIPO DE DOCUMENTO DE IDENTIFICACION'],
            ['nombre'=>'NACIONALIDAD','descripcion'=>'NACIONALIDAD'],
            ['nombre'=>'TIPO_VIA','descripcion'=>'VIA'],
            ['nombre'=>'TIPO_ZONA','descripcion'=>'ZONA'],
            ['nombre'=>'TIPO_TRABAJADOR','descripcion'=>'TIPO DE TRABAJADOR, PENSIONISTA O PRESTADOR DE SERVICIOS'],
            ['nombre'=>'SITUACION_EDUCATIVA','descripcion'=>'SITUACION EDUCATIVA'],
            ['nombre'=>'OCUPACION','descripcion'=>'OCUPACION APLICABLE A TRABAJ. DE SECTOR PUBLICO, OTRAS ENTIDADES Y PERS. EN FORMACION'],
            ['nombre'=>'REGIMEN_PENSIONARIO','descripcion'=>'REGIMEN PENSIONARIO'],
            ['nombre'=>'TIPO_CONTRATO','descripcion'=>'TIPO DE CONTRATO DE TRABAJO/CONDICION LABORAL'],
            ['nombre'=>'PERIODICIDAD','descripcion'=>'PERIODICIDAD DE LA REMUNERACIÓN O INGRESO'],
            ['nombre'=>'EPS','descripcion'=>'ENTIDADES PRESTADORAS DE SERVICIOS-EPS/SERVICIOS PROPIOS'],
            ['nombre'=>'SITUACION_TRABAJADOR','descripcion'=>'SITUACION DEL TRABAJADOR O PENSIONISTA'],
            ['nombre'=>'TIPO_PAGO','descripcion'=>'TIPO DE PAGO'],
            ['nombre'=>'MOTIVO_BAJA','descripcion'=>'MOTIVO DEL FIN DEL CONTRATO O DE LA BAJA EN T-REGISTRO'],
            ['nombre'=>'TIPO_MODALIDAD_FORM','descripcion'=>'TIPO DE MODALIDAD FORMATIVA'],
            ['nombre'=>'CATEG_OCUPACION_TRAB','descripcion'=>'CATEGORIA OCUPACIONAL DEL TRABADOR'],
            ['nombre'=>'PAIS_EMISOR_DOC','descripcion'=>'PAIS EMISOR DE DOCUMENTO'],
            ['nombre'=>'CDLN','descripcion'=>'CODIGO DE LARGA DISTANCIA NACIONAL'],
            ['nombre'=>'OCUPACION_SECT_PRIV','descripcion'=>'OCUPACION APLICABLE AL SECTOR PRIVADO'],
            ['nombre'=>'PAIS_EMISOR_DOC','descripcion'=>'PAIS EMISOR DE DOCUMENTO'],
            ['nombre'=>'PLIEGO_PRESUP','descripcion'=>'PLIEGO PRESUPUESTAL'],
            ['nombre'=>'REGIMEN_ASEG_SALUD','descripcion'=>'REGIMEN DE ASEGURAMIENTO ESSALUD'],
            ['nombre'=>'REGIMEN_LABORAL','descripcion'=>'REGIMEN LABORAL'],
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>10,'codigo'=>'01','nombre'=>'A PLAZO INDETERMINADO - D.LEG. 728','abreviatura'=>'A PLAZO INDET - D.LEG. 728'],
            ['catalogo_id'=>10,'codigo'=>'02','nombre'=>'A TIEMPO PARCIAL','abreviatura'=>'A TIEMPO PARCIAL'],
            ['catalogo_id'=>10,'codigo'=>'03','nombre'=>'POR INICIO O INCREMENTO DE ACTIVIDAD','abreviatura'=>'POR INICIO O INCREM DE ACTIV'],
            ['catalogo_id'=>10,'codigo'=>'04','nombre'=>'POR NECESIDADES DEL MERCADO','abreviatura'=>'POR NECES DEL MERCADO'],
            ['catalogo_id'=>10,'codigo'=>'05','nombre'=>'POR RECONVERSIÓN EMPRESARIAL','abreviatura'=>'POR RECONV EMPRESARIAL'],
            ['catalogo_id'=>10,'codigo'=>'06','nombre'=>'OCASIONAL','abreviatura'=>'OCASIONAL'],
            ['catalogo_id'=>10,'codigo'=>'07','nombre'=>'DE SUPLENCIA','abreviatura'=>'DE SUPLENCIA'],
            ['catalogo_id'=>10,'codigo'=>'08','nombre'=>'DE EMERGENCIA','abreviatura'=>'DE EMERGENCIA'],
            ['catalogo_id'=>10,'codigo'=>'09','nombre'=>'PARA OBRA DETERMINADA O SERVICIO ESPECÍFICO','abreviatura'=>'OBRA DETERM O SERV ESPEC'],
            ['catalogo_id'=>10,'codigo'=>'10','nombre'=>'INTERMITENTE','abreviatura'=>'INTERMITENTE'],
            ['catalogo_id'=>10,'codigo'=>'11','nombre'=>'DE TEMPORADA','abreviatura'=>'DE TEMPORADA'],
            ['catalogo_id'=>10,'codigo'=>'12','nombre'=>'DE EXPORTACIÓN NO TRADICIONAL D.LEY 22342','abreviatura'=>'DE EXPORT. NO TRADIC.'],
            ['catalogo_id'=>10,'codigo'=>'13','nombre'=>'DE EXTRANJERO - D.LEG.689','abreviatura'=>'DE EXTRANJERO - D.LEG. 689'],
            ['catalogo_id'=>10,'codigo'=>'14','nombre'=>'ADMINISTRATIVO DE SERVICIOS - D.LEG 1057 (1)','abreviatura'=>'CAS  - D.LEG 1057'],
            ['catalogo_id'=>10,'codigo'=>'15','nombre'=>'NOMBRADO - D.LEG. N.° 276 (1)','abreviatura'=>'NOMBRADO - D.LEG. N.° 276 (1)'],
            ['catalogo_id'=>10,'codigo'=>'16','nombre'=>'SERVICIOS PERSONALES  - APLICABLES A LOS REGÍM. DE CARRERA (1)','abreviatura'=>'SERV. PERS  - REGÍM. DE CARRERA (1)'],
            ['catalogo_id'=>10,'codigo'=>'17','nombre'=>'GERENTE PÚBLICO - D.LEG. 1024 (1)','abreviatura'=>'GERENTE PÚBLICO - DL 1024'],
            ['catalogo_id'=>10,'codigo'=>'18','nombre'=>'A DOMICILIO','abreviatura'=>'A DOMICILIO'],
            ['catalogo_id'=>10,'codigo'=>'19','nombre'=>'FUTBOLISTAS PROFESIONALES','abreviatura'=>'FUTBOLISTAS PROFESIONALES'],
            ['catalogo_id'=>10,'codigo'=>'20','nombre'=>'AGRARIO - LEY 27360','abreviatura'=>'AGRARIO - LEY 27360'],
            ['catalogo_id'=>10,'codigo'=>'21','nombre'=>'MIGRANTE ANDINO DECISIÓN 545','abreviatura'=>'MIGRANTE ANDINO '],
            ['catalogo_id'=>10,'codigo'=>'99','nombre'=>'OTROS NO PREVISTOS','abreviatura'=>'OTROS NO PREVISTOS']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>15,'codigo'=>'01','nombre'=>'RENUNCIA','abreviatura'=>'RENUNCIA'],
            ['catalogo_id'=>15,'codigo'=>'02','nombre'=>'RENUNCIA CON INCENTIVOS','abreviatura'=>'RENUNCIA CON INCENTIVOS'],
            ['catalogo_id'=>15,'codigo'=>'03','nombre'=>'DESPIDO O DESTITUCIÓN','abreviatura'=>'DESPIDO O DESTITUCIÓN'],
            ['catalogo_id'=>15,'codigo'=>'04','nombre'=>'CESE COLECTIVO','abreviatura'=>'CESE COLECTIVO'],
            ['catalogo_id'=>15,'codigo'=>'05','nombre'=>'JUBILACIÓN','abreviatura'=>'JUBILACIÓN'],
            ['catalogo_id'=>15,'codigo'=>'06','nombre'=>'INVALIDEZ ABSOLUTA PERMANENTE','abreviatura'=>'INVALIDEZ ABSOLUTA PERMAN'],
            ['catalogo_id'=>15,'codigo'=>'07','nombre'=>'TERMINACIÓN DE LA OBRA O SERVICIO, CUMPLIMIENTO CONDICIÓN RESOLUTORIA O VENCIMIENTO DEL PLAZO','abreviatura'=>'TERMIN OBRA/SERV, CUMPLIM CONDIC RESOL. O VENC PLAZO'],
            ['catalogo_id'=>15,'codigo'=>'08','nombre'=>'MUTUO DISENSO','abreviatura'=>'MUTUO DISENSO'],
            ['catalogo_id'=>15,'codigo'=>'09','nombre'=>'FALLECIMIENTO','abreviatura'=>'FALLECIMIENTO'],
            ['catalogo_id'=>15,'codigo'=>'10','nombre'=>'SUSPENSIÓN DE LA PENSIÓN (1)','abreviatura'=>'SUSPENSIÓN DE LA PENSIÓN'],
            ['catalogo_id'=>15,'codigo'=>'11','nombre'=>'REASIGNACIÓN SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA(2)','abreviatura'=>'REASIGNACIÓN'],
            ['catalogo_id'=>15,'codigo'=>'12','nombre'=>'PERMUTA SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA (2)','abreviatura'=>'PERMUTA'],
            ['catalogo_id'=>15,'codigo'=>'13','nombre'=>'TRANSFERENCIA SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA (2)','abreviatura'=>'TRANSFERENCIA'],
            ['catalogo_id'=>15,'codigo'=>'14','nombre'=>'BAJA POR SUCESIÓN EN POSICIÓN DEL EMPLEADOR','abreviatura'=>'BAJA POR SUC. EN POSIC DEL EMPLEADOR'],
            ['catalogo_id'=>15,'codigo'=>'15','nombre'=>'EXTINCIÓN O LIQUIDACIÓN DEL EMPLEADOR','abreviatura'=>'EXTINCIÓN O LIQUID. DEL EMPLEADOR'],
            ['catalogo_id'=>15,'codigo'=>'16','nombre'=>'OTROS MOTIVOS DE CADUCIDAD DE LA PENSIÓN (1)','abreviatura'=>'OTR MOTIV CADUC PENSIÓN '],
            ['catalogo_id'=>15,'codigo'=>'17','nombre'=>'NO SE INICIÓ LA RELACIÓN LABORAL O PRESTACIÓN EFECTIVA DE SERVICIOS','abreviatura'=>'NO SE INICIÓ LA REL.  LABORAL O PREST. DE SERVICIOS'],
            ['catalogo_id'=>15,'codigo'=>'18','nombre'=>'LÍMITE DE EDAD 70 AÑOS ','abreviatura'=>'LÍMITE DE EDAD 70 AÑOS '],
            ['catalogo_id'=>15,'codigo'=>'19','nombre'=>'OTRAS CAUSALES RÉGIMEN PÚBLICO GENERAL SERVICIO CIVIL - LEY 30057','abreviatura'=>'OTRAS CAUSALES – LEY 30057'],
            ['catalogo_id'=>15,'codigo'=>'20','nombre'=>'INHABILITACIÓN PARA EL EJERCICIO PROFESIONAL O DE LA FUNCIÓN PÚBLICA POR MÁS DE TRES MESES - LEY 30057','abreviatura'=>'INHAB. PARA EJER.PROF. O FUNC.PUB. MÁS DE 3 MESES LEY 30057'],
            ['catalogo_id'=>15,'codigo'=>'99','nombre'=>'SIN VÍNCULO LABORAL - HABILITADO PARA PDT PLAME','abreviatura'=>'SVL -HABILITADO PARA PDT PLAME (3)']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>1,'codigo'=>'1110','nombre'=>'CULTIVOS DE CEREALES.'],
            ['catalogo_id'=>1,'codigo'=>'1123','nombre'=>'CULTIVO DE HORTALIZAS Y LEGUMBRES.'],
            ['catalogo_id'=>1,'codigo'=>'1136','nombre'=>'CULTIVO DE FRUTAS.'],
            ['catalogo_id'=>1,'codigo'=>'1211','nombre'=>'CRIA DE GANADO.'],
            ['catalogo_id'=>1,'codigo'=>'1224','nombre'=>'CRIA DE ANIMALES DOMESTICOS.'],
            ['catalogo_id'=>1,'codigo'=>'1300','nombre'=>'EXPLOTACION MIXTA.'],
            ['catalogo_id'=>1,'codigo'=>'1400','nombre'=>'SERVICIOS AGRICOLAS, GANADERAS.'],
            ['catalogo_id'=>1,'codigo'=>'1501','nombre'=>'CAZA ORDINARIA Y SERVICIOS CONEXOS.'],
            ['catalogo_id'=>1,'codigo'=>'2003','nombre'=>'SILVICULTURA Y EXT. DE MADERA.'],
            ['catalogo_id'=>1,'codigo'=>'5002','nombre'=>'PESCA, EXPLOT. CRIADEROS DE PECES.'],
            ['catalogo_id'=>1,'codigo'=>'10100','nombre'=>'EXTRAC. Y  AGLOMERAC. CARBON DE PIEDRA.'],
            ['catalogo_id'=>1,'codigo'=>'10200','nombre'=>'EXTRAC. Y AGLOMERAC. LIGNITO.'],
            ['catalogo_id'=>1,'codigo'=>'10301','nombre'=>'EXTRAC. Y AGLOMERAC. DE TURBA.'],
            ['catalogo_id'=>1,'codigo'=>'11106','nombre'=>'EXT. PETROLEO CRUDO Y GAS NATURAL.'],
            ['catalogo_id'=>1,'codigo'=>'11207','nombre'=>'SERV. PETROLEROS Y DE GAS..'],
            ['catalogo_id'=>1,'codigo'=>'12001','nombre'=>'EXT. DE MIN. URANIO Y TORIO'],
            ['catalogo_id'=>1,'codigo'=>'13109','nombre'=>'EXT. DE MIN. DE HIERRO'],
            ['catalogo_id'=>1,'codigo'=>'13200','nombre'=>'EXT. DE MIN. METALIFEROS NO FERROSOS.'],
            ['catalogo_id'=>1,'codigo'=>'14105','nombre'=>'EXT. DE PIEDRA, ARENA Y ARCILLA.'],
            ['catalogo_id'=>1,'codigo'=>'14219','nombre'=>'EXT. MIN FABRIC. ABONO Y PROD. QUIMIC.'],
            ['catalogo_id'=>1,'codigo'=>'14221','nombre'=>'EXTRACCION DE SAL.'],
            ['catalogo_id'=>1,'codigo'=>'14290','nombre'=>'EXP. OTRAS MINAS Y CANTERAS NIA.'],
            ['catalogo_id'=>1,'codigo'=>'15114','nombre'=>'PRODUC. CARNE Y PROD. CARNICOS.'],
            ['catalogo_id'=>1,'codigo'=>'15127','nombre'=>'ELAB. Y CONS DE PESCADO.'],
            ['catalogo_id'=>1,'codigo'=>'15130','nombre'=>'ELAB. FRUTAS, LEG. Y HORTALIZAS.'],
            ['catalogo_id'=>1,'codigo'=>'15142','nombre'=>'ELAB. DE ACEITE Y GRASAS.'],
            ['catalogo_id'=>1,'codigo'=>'15202','nombre'=>'ELAB DE PRODUCTOS LACTEOS.'],
            ['catalogo_id'=>1,'codigo'=>'15316','nombre'=>'ELAB. DE PRODUCTOS DE MOLINERIA.'],
            ['catalogo_id'=>1,'codigo'=>'15329','nombre'=>'ELAB DE ALMIDONES Y DERIVADOS.'],
            ['catalogo_id'=>1,'codigo'=>'15331','nombre'=>'ELAB. DE PIENSOS PREPARADOS.'],
            ['catalogo_id'=>1,'codigo'=>'15417','nombre'=>'ELAB. PROD. DE PANADERIA.'],
            ['catalogo_id'=>1,'codigo'=>'15420','nombre'=>'ELAB. DE AZUCAR.'],
            ['catalogo_id'=>1,'codigo'=>'15432','nombre'=>'ELAB. CACAO, CHOCOLATE Y CONFIT.'],
            ['catalogo_id'=>1,'codigo'=>'15445','nombre'=>'ELAB. MACARRONES, FIDEOS Y OTROS.'],
            ['catalogo_id'=>1,'codigo'=>'15499','nombre'=>'ELAB DE OTROS PROD. ALIMENTICIOS.'],
            ['catalogo_id'=>1,'codigo'=>'15518','nombre'=>'MEZCLA DE BEBIDAS ALCOHOLICAS.'],
            ['catalogo_id'=>1,'codigo'=>'15520','nombre'=>'ELAB. DE VINOS.'],
            ['catalogo_id'=>1,'codigo'=>'15533','nombre'=>'ELAB. DE BEBIDAS MALTEADAS.'],
            ['catalogo_id'=>1,'codigo'=>'15546','nombre'=>'ELAB. DE BEBIDAS NO ALCOHOLICAS.'],
            ['catalogo_id'=>1,'codigo'=>'16007','nombre'=>'ELAB. DE PRODUCTOS DE TABACO.'],
            ['catalogo_id'=>1,'codigo'=>'17117','nombre'=>'PREP Y TEJ DE FIBRAS TEXTILES.'],
            ['catalogo_id'=>1,'codigo'=>'17120','nombre'=>'ACABADO DE PROD. TEXTILES.'],
            ['catalogo_id'=>1,'codigo'=>'17218','nombre'=>'FAB. ART. CONFECCIONADOS.'],
            ['catalogo_id'=>1,'codigo'=>'17220','nombre'=>'FAB. DE TAPICES Y ALFOMBRAS.'],
            ['catalogo_id'=>1,'codigo'=>'17233','nombre'=>'FAB. CUERDAS, CORDELES Y REDES.'],
            ['catalogo_id'=>1,'codigo'=>'17290','nombre'=>'FAB. OTROS PROD. TEXTILES NEOP.'],
            ['catalogo_id'=>1,'codigo'=>'17306','nombre'=>'FAB. TEJIDOS Y ART DE PUNTO.'],
            ['catalogo_id'=>1,'codigo'=>'18100','nombre'=>'FAB. DE PRENDAS DE VESTIR.'],
            ['catalogo_id'=>1,'codigo'=>'18201','nombre'=>'FAB. DE ARTICULOS DE PIEL.'],
            ['catalogo_id'=>1,'codigo'=>'19110','nombre'=>'CURTIDO Y ADOBO DE CUEROS.'],
            ['catalogo_id'=>1,'codigo'=>'19122','nombre'=>'FAB. DE MALETAS Y OTROS.'],
            ['catalogo_id'=>1,'codigo'=>'19208','nombre'=>'FAB. DE CALZADO.'],
            ['catalogo_id'=>1,'codigo'=>'20108','nombre'=>'ASERRADO Y ACEPILLADURA MADERA.'],
            ['catalogo_id'=>1,'codigo'=>'20211','nombre'=>'FAB. DE HOJAS DE MADERA.'],
            ['catalogo_id'=>1,'codigo'=>'20224','nombre'=>'FAB. PARTES Y PIEZAS CARPINTERIA.'],
            ['catalogo_id'=>1,'codigo'=>'20237','nombre'=>'FAB. RECIPIENTES DE MADERA.'],
            ['catalogo_id'=>1,'codigo'=>'20293','nombre'=>'FAB. OTROS PRODUCTOS DE MADERA.'],
            ['catalogo_id'=>1,'codigo'=>'21016','nombre'=>'FAB. DE PAPEL Y CARTON.'],
            ['catalogo_id'=>1,'codigo'=>'21029','nombre'=>'FAB.  ENVASES DE PAPEL Y CARTON.'],
            ['catalogo_id'=>1,'codigo'=>'21098','nombre'=>'FAB. DE OTROS ARTICULOS.'],
            ['catalogo_id'=>1,'codigo'=>'22113','nombre'=>'ED. LIBROS, FOLLETOS Y OTROS.'],
            ['catalogo_id'=>1,'codigo'=>'22126','nombre'=>'ED. DE PERIODICOS Y REVISTAS.'],
            ['catalogo_id'=>1,'codigo'=>'22139','nombre'=>'ED. DE MATERIALES GRABADOS.'],
            ['catalogo_id'=>1,'codigo'=>'22195','nombre'=>'OTROS TRABAJOS DE EDICION.'],
            ['catalogo_id'=>1,'codigo'=>'22214','nombre'=>'ACTIVIDADES DE IMPRESION.'],
            ['catalogo_id'=>1,'codigo'=>'22227','nombre'=>'SERVICIOS RDOS CON IMPRESION.'],
            ['catalogo_id'=>1,'codigo'=>'22302','nombre'=>'REPRODUCCION MATERIALES GRAB.'],
            ['catalogo_id'=>1,'codigo'=>'23107','nombre'=>'FAB. PROD. DE HORNOS DE COQUE.'],
            ['catalogo_id'=>1,'codigo'=>'23208','nombre'=>'FAB. PROD.  REFINACION DEL PETROLEO.'],
            ['catalogo_id'=>1,'codigo'=>'23309','nombre'=>'ELAB. DE COMBUSTIBLES NUCLEAR.'],
            ['catalogo_id'=>1,'codigo'=>'24116','nombre'=>'FAB. DE SUSTANCIAS QUIMICAS BASICAS.'],
            ['catalogo_id'=>1,'codigo'=>'24129','nombre'=>'FAB. ABONO  Y COMP. DE NITROGENO.'],
            ['catalogo_id'=>1,'codigo'=>'24131','nombre'=>'FAB. DE PLASTICOS Y DE CAUCHO.'],
            ['catalogo_id'=>1,'codigo'=>'24217','nombre'=>'FAB. DE PLAGUICIDAS Y OTROS PROD. QUIM.'],
            ['catalogo_id'=>1,'codigo'=>'24220','nombre'=>'FAB. DE PINTURAS Y BARNICES.'],
            ['catalogo_id'=>1,'codigo'=>'24232','nombre'=>'FAB. DE PROD. FARMACEUTICOS.'],
            ['catalogo_id'=>1,'codigo'=>'24245','nombre'=>'FAB. JABONES Y DETERGENTES.'],
            ['catalogo_id'=>1,'codigo'=>'24299','nombre'=>'FAB. DE OTROS PROD. QUIMICOS NEOP.'],
            ['catalogo_id'=>1,'codigo'=>'24305','nombre'=>'FAB. DE FIBRAS SINTETICAS O ARTIFIC.'],
            ['catalogo_id'=>1,'codigo'=>'25112','nombre'=>'FAB. DE CUBIERTOS DE CAUCHO.'],
            ['catalogo_id'=>1,'codigo'=>'25194','nombre'=>'FAB. OTROS PRODUCTOS DE CAUCHO.'],
            ['catalogo_id'=>1,'codigo'=>'25200','nombre'=>'FAB. DE PRODUCTOS DE PLASTICOS.'],
            ['catalogo_id'=>1,'codigo'=>'26106','nombre'=>'FAB. VIDRIO Y PROD. DE VIDRIO'],
            ['catalogo_id'=>1,'codigo'=>'26916','nombre'=>'FAB. PROD. CERAMICA NO REFRACT. N. EST.'],
            ['catalogo_id'=>1,'codigo'=>'26929','nombre'=>'FAB. PROD. CERAMICA REFACTARIA.'],
            ['catalogo_id'=>1,'codigo'=>'26931','nombre'=>'FAB. PROD. CERAMICA NO REFRACT. EST.'],
            ['catalogo_id'=>1,'codigo'=>'26944','nombre'=>'FAB. DE CEMENTO, CAL Y YESO.'],
            ['catalogo_id'=>1,'codigo'=>'26957','nombre'=>'FAB.  ART. DE HORMIGON, CEMENTO Y YESO.'],
            ['catalogo_id'=>1,'codigo'=>'26960','nombre'=>'CORTE, TALLADO Y ACABADO DE PIEDRA.'],
            ['catalogo_id'=>1,'codigo'=>'26998','nombre'=>'FAB. OTROS PROD. MIN. NO METALIC. NCP.'],
            ['catalogo_id'=>1,'codigo'=>'27102','nombre'=>'FAB. PRODUCTOS DE HIERRO Y ACERO.'],
            ['catalogo_id'=>1,'codigo'=>'27203','nombre'=>'FAB. PRODUCTOS DE MET. PRECIOSOS.'],
            ['catalogo_id'=>1,'codigo'=>'27317','nombre'=>'FUNDICION DE HIERRO Y DE ACERO.'],
            ['catalogo_id'=>1,'codigo'=>'27320','nombre'=>'FUNDICION DE METALES NO FERROSOS.'],
            ['catalogo_id'=>1,'codigo'=>'28111','nombre'=>'FAB. PROD. METAL. USO ESTRUCTURAL.'],
            ['catalogo_id'=>1,'codigo'=>'28124','nombre'=>'FAB. TANQUES, DEPOSITOS Y RECIP. METAL.'],
            ['catalogo_id'=>1,'codigo'=>'28137','nombre'=>'FAB.  DE GENERADORES DE VAPOR.'],
            ['catalogo_id'=>1,'codigo'=>'28919','nombre'=>'FAB. PROD. MET. ACABADOS O SEMIACABAD.'],
            ['catalogo_id'=>1,'codigo'=>'28921','nombre'=>'OBRAS DE INGENIERIA MECANICA.'],
            ['catalogo_id'=>1,'codigo'=>'28934','nombre'=>'FAB.  ART. CUCHILLERIA, FERRETERIA.'],
            ['catalogo_id'=>1,'codigo'=>'28990','nombre'=>'FAB. OTROS PROD. DE METAL NCP.'],
            ['catalogo_id'=>1,'codigo'=>'29118','nombre'=>'FAB. DE MOTORES Y TURBINAS.'],
            ['catalogo_id'=>1,'codigo'=>'29120','nombre'=>'FAB. DE BOMBAS,  COMPRESORAS, GRIFOS.'],
            ['catalogo_id'=>1,'codigo'=>'29133','nombre'=>'FAB.  COJINETES Y ENGRANAJES.'],
            ['catalogo_id'=>1,'codigo'=>'29146','nombre'=>'FAB. HORNOS, HOGUERAS, QUEMADORES.'],
            ['catalogo_id'=>1,'codigo'=>'29159','nombre'=>'FAB. EQUIP.  ELEVACION Y MANIPULACION.'],
            ['catalogo_id'=>1,'codigo'=>'29190','nombre'=>'FAB. OTRO TIPO MAQUINARIA USO GRAL.'],
            ['catalogo_id'=>1,'codigo'=>'29219','nombre'=>'FAB. DE MAQUINARIA  AGROPECUARIA.'],
            ['catalogo_id'=>1,'codigo'=>'29221','nombre'=>'FAB. DE MAQUINAS HERRAMIENTA.'],
            ['catalogo_id'=>1,'codigo'=>'29234','nombre'=>'FAB. DE MAQUINARIA  METALURGICA.'],
            ['catalogo_id'=>1,'codigo'=>'29247','nombre'=>'FAB. MAQUIN MINERA Y OBRAS DE CONST.'],
            ['catalogo_id'=>1,'codigo'=>'29250','nombre'=>'FAB. MAQUIN. ELAB. ALIMENTOS, BEBIDAS.'],
            ['catalogo_id'=>1,'codigo'=>'29262','nombre'=>'FAB. MAQUINARIA ELAB. TEXTILES.'],
            ['catalogo_id'=>1,'codigo'=>'29275','nombre'=>'FAB. DE ARMAS Y MUNICIONES.'],
            ['catalogo_id'=>1,'codigo'=>'29290','nombre'=>'FAB. OTRO TIPO MAQUIN. USO ESPECIAL.'],
            ['catalogo_id'=>1,'codigo'=>'29307','nombre'=>'FAB.  APARATOS DE USO DOMESTICO NCP.'],
            ['catalogo_id'=>1,'codigo'=>'30005','nombre'=>'FAB.  MAQUINARIA DE OFICINA.'],
            ['catalogo_id'=>1,'codigo'=>'31102','nombre'=>'FAB.  MOTORES,  GENERADORES ELECTRICOS.'],
            ['catalogo_id'=>1,'codigo'=>'31203','nombre'=>'FAB. DE APARATOS DE DISTRIBUCION.'],
            ['catalogo_id'=>1,'codigo'=>'31304','nombre'=>'FAB. DE HILOS Y CABLES AISLADOS.'],
            ['catalogo_id'=>1,'codigo'=>'31405','nombre'=>'FAB. DE ACUMULADORES Y BATERIAS.'],
            ['catalogo_id'=>1,'codigo'=>'31506','nombre'=>'FAB. DE LAMPARAS ELECTRICAS.'],
            ['catalogo_id'=>1,'codigo'=>'31900','nombre'=>'FAB. OTRO TIPO EQUIPO ELECTRICO NCP.'],
            ['catalogo_id'=>1,'codigo'=>'32109','nombre'=>'FAB. TUBOS Y VALVULAS ELECTRONICOS.'],
            ['catalogo_id'=>1,'codigo'=>'32200','nombre'=>'FAB. TRANSMISORES DE RADIO Y TV.'],
            ['catalogo_id'=>1,'codigo'=>'32300','nombre'=>'FAB. RECEPTORES DE RADIO Y TV.'],
            ['catalogo_id'=>1,'codigo'=>'33118','nombre'=>'FAB. EQUIPO MEDICO Y QUIRURGICO.'],
            ['catalogo_id'=>1,'codigo'=>'33120','nombre'=>'FAB. INSTRUMENTOS DE MEDICION.'],
            ['catalogo_id'=>1,'codigo'=>'33133','nombre'=>'FAB. EQUIPO CONTROL DE PROCESOS IND.'],
            ['catalogo_id'=>1,'codigo'=>'33206','nombre'=>'FAB. INSTRUMENTOS OPTICOS.'],
            ['catalogo_id'=>1,'codigo'=>'33307','nombre'=>'FAB. DE RELOJES.'],
            ['catalogo_id'=>1,'codigo'=>'34101','nombre'=>'FAB. VEHICULOS AUTOMOTORES.'],
            ['catalogo_id'=>1,'codigo'=>'34202','nombre'=>'FAB. CARROCERIAS PARA VEHICULOS.'],
            ['catalogo_id'=>1,'codigo'=>'34303','nombre'=>'FAB. PARTES, PIEZAS Y ACCESORIOS.'],
            ['catalogo_id'=>1,'codigo'=>'35110','nombre'=>'CONSTRUCCION Y REPARACION  DE BUQUES.'],
            ['catalogo_id'=>1,'codigo'=>'35123','nombre'=>'CONSTRUC. Y REPARAC. DE EMBARCACIONES.'],
            ['catalogo_id'=>1,'codigo'=>'35209','nombre'=>'FAB. LOCOMOTORAS Y MATERIAL RODANTE.'],
            ['catalogo_id'=>1,'codigo'=>'35300','nombre'=>'FAB. AERONAVES Y NAVES ESPACIALES.'],
            ['catalogo_id'=>1,'codigo'=>'35918','nombre'=>'FAB. DE MOTOCICLETAS.'],
            ['catalogo_id'=>1,'codigo'=>'35920','nombre'=>'FAB. BICICLETAS Y SILLONES DE RUEDAS.'],
            ['catalogo_id'=>1,'codigo'=>'35990','nombre'=>'FAB. OTROS EQUIPOS DE  TRANSPORTE NCP.'],
            ['catalogo_id'=>1,'codigo'=>'36104','nombre'=>'FAB. DE MUEBLES.'],
            ['catalogo_id'=>1,'codigo'=>'36914','nombre'=>'FAB. JOYAS Y ARTICULOS CONEXOS.'],
            ['catalogo_id'=>1,'codigo'=>'36927','nombre'=>'FAB. INSTRUMENTOS MUSICALES.'],
            ['catalogo_id'=>1,'codigo'=>'36930','nombre'=>'FAB. ARTICULOS DEPORTIVOS.'],
            ['catalogo_id'=>1,'codigo'=>'36942','nombre'=>'FAB. DE JUEGOS Y JUGUETES.'],
            ['catalogo_id'=>1,'codigo'=>'36996','nombre'=>'OTRAS INDUSTRIAS  MANUFACTURERAS NCP.'],
            ['catalogo_id'=>1,'codigo'=>'37100','nombre'=>'RECICLAMIENTO DESPERDICIOS METALIC.'],
            ['catalogo_id'=>1,'codigo'=>'37201','nombre'=>'RECICLAMIENTO DESPERDICIOS NO METAL.'],
            ['catalogo_id'=>1,'codigo'=>'40104','nombre'=>'GENERACION  Y DIST. ENERGIA ELECTRICA.'],
            ['catalogo_id'=>1,'codigo'=>'40205','nombre'=>'FAB. DE GAS, DISTRIBUCION COMBUSTIBLE.'],
            ['catalogo_id'=>1,'codigo'=>'40306','nombre'=>'SUMINISTRO DE VAPOR Y AGUA CALIENTE.'],
            ['catalogo_id'=>1,'codigo'=>'41000','nombre'=>'CAPTACION ,  DEPURACION  Y DIST. DE AGUA'],
            ['catalogo_id'=>1,'codigo'=>'45106','nombre'=>'PREPARACION DEL TERRENO.'],
            ['catalogo_id'=>1,'codigo'=>'45207','nombre'=>'CONSTRUCCION EDIFICIOS COMPLETOS.'],
            ['catalogo_id'=>1,'codigo'=>'45308','nombre'=>'ACONDICIONAMINTO DE EDIFICIOS.'],
            ['catalogo_id'=>1,'codigo'=>'45409','nombre'=>'TERMINACION DE EDIFICIOS.'],
            ['catalogo_id'=>1,'codigo'=>'45500','nombre'=>'ALQUILER DE CONSTRUCCION.'],
            ['catalogo_id'=>1,'codigo'=>'50102','nombre'=>'VENTA DE VEHICULOS AUTOMOTORES.'],
            ['catalogo_id'=>1,'codigo'=>'50203','nombre'=>'MANTENIMIENTO Y REPARAC. VEHICULOS.'],
            ['catalogo_id'=>1,'codigo'=>'50304','nombre'=>'VENTA PARTES, PIEZAS, ACCESORIOS.'],
            ['catalogo_id'=>1,'codigo'=>'50405','nombre'=>'VENTA, MANTEN. Y REPARAC. MOTOCICLETAS.'],
            ['catalogo_id'=>1,'codigo'=>'50506','nombre'=>'VENTA AL POR MENOR COMBUSTIBLES.'],
            ['catalogo_id'=>1,'codigo'=>'51109','nombre'=>'VTA.  MAY. A CAMBIO DE UNA RETRIBUCION.'],
            ['catalogo_id'=>1,'codigo'=>'51212','nombre'=>'VTA.  MAY. DE MATERIAS PRIMAS AGROPEC.'],
            ['catalogo_id'=>1,'codigo'=>'51225','nombre'=>'VTA. MAY. ALIMENTOS, BEBIDAS Y TABACO.'],
            ['catalogo_id'=>1,'codigo'=>'51313','nombre'=>'VTA. MAY. PRODUCTOS TEXTILES.'],
            ['catalogo_id'=>1,'codigo'=>'51395','nombre'=>'VTA. MAY. OTROS ENSERES DOMESTICOS.'],
            ['catalogo_id'=>1,'codigo'=>'51414','nombre'=>'VTA. AL POR MAYOR DE COMBUSTIBLES.'],
            ['catalogo_id'=>1,'codigo'=>'51427','nombre'=>'VTA. MAY. DE METALES Y MINERALES MET.'],
            ['catalogo_id'=>1,'codigo'=>'51430','nombre'=>'VTA. MAY. MATERIALES DE CONSTRUCCION.'],
            ['catalogo_id'=>1,'codigo'=>'51496','nombre'=>'VTA. MAY. OTROS PRODUCTOS INTERMEDIOS.'],
            ['catalogo_id'=>1,'codigo'=>'51502','nombre'=>'VTA. MAY. MAQUINARIA, EQUIPO Y MATER.'],
            ['catalogo_id'=>1,'codigo'=>'51906','nombre'=>'VTA. MAY. DE OTROS PRODUCTOS.'],
            ['catalogo_id'=>1,'codigo'=>'52118','nombre'=>'VTA. MIN. EN ALMACENES NO ESPECIALIZ.'],
            ['catalogo_id'=>1,'codigo'=>'52190','nombre'=>'VTA.  MIN. OTROS PRODUCTOS EN ALMACEN.'],
            ['catalogo_id'=>1,'codigo'=>'52206','nombre'=>'VTA.  MIN. ALIMENTOS, BEBIDAS, TABACO.'],
            ['catalogo_id'=>1,'codigo'=>'52310','nombre'=>'VTA.  MIN. PROD. FARMAC. Y ART. TOCADOR.'],
            ['catalogo_id'=>1,'codigo'=>'52322','nombre'=>'VTA. MIN. PRODUCTOS TEXTILES, CALZADO.'],
            ['catalogo_id'=>1,'codigo'=>'52335','nombre'=>'VTA. MIN. EQUIPO DE USO DOMESTICO.'],
            ['catalogo_id'=>1,'codigo'=>'52348','nombre'=>'VTA. MIN. ARTICULOS DE FERRETERIA.'],
            ['catalogo_id'=>1,'codigo'=>'52391','nombre'=>'OTROS TIPOS DE VENTA AL POR MENOR.'],
            ['catalogo_id'=>1,'codigo'=>'52408','nombre'=>'VTA. MIN. DE ALMACENES DE ART. USADOS.'],
            ['catalogo_id'=>1,'codigo'=>'52511','nombre'=>'VTA. MIN. DE CASAS DE VENTA POR CORREO.'],
            ['catalogo_id'=>1,'codigo'=>'52524','nombre'=>'VTA. MIN. EN PUESTOS DE VENTA.'],
            ['catalogo_id'=>1,'codigo'=>'52593','nombre'=>'OTROS TIPOS DE VENTA POR MENOR.'],
            ['catalogo_id'=>1,'codigo'=>'52600','nombre'=>'REPARACION DE EFECTOS PERSONALES.'],
            ['catalogo_id'=>1,'codigo'=>'55104','nombre'=>'HOTELES, CAMPAMENTOS Y OTROS.'],
            ['catalogo_id'=>1,'codigo'=>'55205','nombre'=>'RESTAURANTES, BARES Y CANTINAS.'],
            ['catalogo_id'=>1,'codigo'=>'60100','nombre'=>'TRANSPORTE POR VIA FERREA.'],
            ['catalogo_id'=>1,'codigo'=>'60214','nombre'=>'OTROS TIPOS TRANSPORTE REG. VIA TER.'],
            ['catalogo_id'=>1,'codigo'=>'60227','nombre'=>'OTROS TIPOS  TRANSPORTE NO REG. VIA TER.'],
            ['catalogo_id'=>1,'codigo'=>'60230','nombre'=>'TRANSPORTE  DE CARGA POR CARRETERA.'],
            ['catalogo_id'=>1,'codigo'=>'60302','nombre'=>'TRANSPORTE POR TUBERIAS.'],
            ['catalogo_id'=>1,'codigo'=>'61107','nombre'=>'TRANSPORTE MARITIMO Y DE CABOTAJE.'],
            ['catalogo_id'=>1,'codigo'=>'61208','nombre'=>'TRANSPORTE VIAS NAVEGACION INTERIOR.'],
            ['catalogo_id'=>1,'codigo'=>'62103','nombre'=>'TRANSPORTE  REGULAR VIA AEREA.'],
            ['catalogo_id'=>1,'codigo'=>'62204','nombre'=>'TRANSPORTE  NO REGULAR  POR VIA AEREA.'],
            ['catalogo_id'=>1,'codigo'=>'63011','nombre'=>'MANIPULACION DE LA CARGA'],
            ['catalogo_id'=>1,'codigo'=>'63024','nombre'=>'ALMACENAMIENTO Y DEPOSITO'],
            ['catalogo_id'=>1,'codigo'=>'63037','nombre'=>'OTRAS ACTIVIDADES DE TRANSPORTES.'],
            ['catalogo_id'=>1,'codigo'=>'63040','nombre'=>'AGENCIAS DE VIAJES Y GUIAS TURISTIC.'],
            ['catalogo_id'=>1,'codigo'=>'63093','nombre'=>'ORGANIZACION DEL TRANSPORTE'],
            ['catalogo_id'=>1,'codigo'=>'64119','nombre'=>'ACTIVIDADES POSTALES NACIONALES'],
            ['catalogo_id'=>1,'codigo'=>'64121','nombre'=>'ACTIVIDADES DE CORREO DISTINTAS'],
            ['catalogo_id'=>1,'codigo'=>'64207','nombre'=>'TELECOMUNICACIONES'],
            ['catalogo_id'=>1,'codigo'=>'65115','nombre'=>'BANCA CENTRAL'],
            ['catalogo_id'=>1,'codigo'=>'65197','nombre'=>'OTROS TIPOS INTERMEDIACION MONETARIA.'],
            ['catalogo_id'=>1,'codigo'=>'65912','nombre'=>'ARRENDAMIENTO CON OPCION DE COMPRA'],
            ['catalogo_id'=>1,'codigo'=>'65925','nombre'=>'OTROS TIPOS DE CREDITO'],
            ['catalogo_id'=>1,'codigo'=>'65994','nombre'=>'OTROS TIPOS DE INTERMEDIACION  FINANC.'],
            ['catalogo_id'=>1,'codigo'=>'66010','nombre'=>'PLANES DE SEGUROS DE VIDA'],
            ['catalogo_id'=>1,'codigo'=>'66023','nombre'=>'PLANES DE PENSIONES'],
            ['catalogo_id'=>1,'codigo'=>'66036','nombre'=>'PLANES DE SEGUROS GENERALES'],
            ['catalogo_id'=>1,'codigo'=>'67118','nombre'=>'ADMINISTRACION MERCADOS FINANCIEROS.'],
            ['catalogo_id'=>1,'codigo'=>'67120','nombre'=>'ACTIVIDADES BURSATILES'],
            ['catalogo_id'=>1,'codigo'=>'67190','nombre'=>'ACTIV. AUXIL ARES DE INTERM. FINANC.'],
            ['catalogo_id'=>1,'codigo'=>'67206','nombre'=>'ACTIV. FINANC. PLANES SEGUROS Y PENS.'],
            ['catalogo_id'=>1,'codigo'=>'70109','nombre'=>'ACTIVIDADES INMOBILIARIAS'],
            ['catalogo_id'=>1,'codigo'=>'70200','nombre'=>'ACTIV. INMOBILIARIAS POR RETRIBUCION.'],
            ['catalogo_id'=>1,'codigo'=>'71118','nombre'=>'ALQUILER EQUIPO TRANSPORTE V. TERRES.'],
            ['catalogo_id'=>1,'codigo'=>'71120','nombre'=>'ALQUILER EQUIPO TRANSPORTE V.ACUAT.'],
            ['catalogo_id'=>1,'codigo'=>'71133','nombre'=>'ALQUILER EQUIPO TRANSPORTE V.AEREA.'],
            ['catalogo_id'=>1,'codigo'=>'71219','nombre'=>'ALQUILER MAQUI. Y EQUIP.AGROPECUARIO.'],
            ['catalogo_id'=>1,'codigo'=>'71221','nombre'=>'ALQUILER MAQUI. Y EQUIP.CONSTRUCCION.'],
            ['catalogo_id'=>1,'codigo'=>'71234','nombre'=>'ALQUILER MAQUI.Y EQUIP.DE OFICINA.'],
            ['catalogo_id'=>1,'codigo'=>'71290','nombre'=>'ALQUILER OTROS TIPOS MAQ.Y EQUI. NCP.'],
            ['catalogo_id'=>1,'codigo'=>'71307','nombre'=>'ALQUILER ENSERES DOMESTICOS NCP.'],
            ['catalogo_id'=>1,'codigo'=>'72101','nombre'=>'CONSULTORES EN EQUIPO INFORMATICA.'],
            ['catalogo_id'=>1,'codigo'=>'72202','nombre'=>'CONSULTORES  PROG. Y SUMIN. INFORMATIC.'],
            ['catalogo_id'=>1,'codigo'=>'72303','nombre'=>'PROCESAMIENTO DE DATOS.'],
            ['catalogo_id'=>1,'codigo'=>'72404','nombre'=>'ACTIV.RELACIONADAS.CON BASE DE DATO.'],
            ['catalogo_id'=>1,'codigo'=>'72505','nombre'=>'MANTEN.Y REPAR.MAQUIN. DE OFICINA.'],
            ['catalogo_id'=>1,'codigo'=>'72909','nombre'=>'OTRAS ACTIVIDADES DE INFORMATICA.'],
            ['catalogo_id'=>1,'codigo'=>'73108','nombre'=>'INVESTIGACION DE CIENCIAS NATURALES.'],
            ['catalogo_id'=>1,'codigo'=>'73209','nombre'=>'INVESTIGACION DE CIENCIAS SOCIALES.'],
            ['catalogo_id'=>1,'codigo'=>'74117','nombre'=>'ACTIVIDADES JURIDICAS'],
            ['catalogo_id'=>1,'codigo'=>'74120','nombre'=>'ACTIVIDADES DE CONTABILIDAD'],
            ['catalogo_id'=>1,'codigo'=>'74132','nombre'=>'INVESTIGACION DE MERCADOS'],
            ['catalogo_id'=>1,'codigo'=>'74145','nombre'=>'ACTIV.DE ASESORAMIENTO EMPRESARIAL'],
            ['catalogo_id'=>1,'codigo'=>'74218','nombre'=>'ACTIV.DE ARQUITECTURA E INGENIERIA'],
            ['catalogo_id'=>1,'codigo'=>'74220','nombre'=>'ENSAYOS Y ANALISIS TECNICOS'],
            ['catalogo_id'=>1,'codigo'=>'74306','nombre'=>'PUBLICIDAD'],
            ['catalogo_id'=>1,'codigo'=>'74914','nombre'=>'OBTENCION Y DOTACION PERSONAL'],
            ['catalogo_id'=>1,'codigo'=>'74927','nombre'=>'ACTIV. DE INVESTIGACION Y SEGURIDAD.'],
            ['catalogo_id'=>1,'codigo'=>'74930','nombre'=>'ACTIVIDADES LIMPIEZA DE EDIFICIOS'],
            ['catalogo_id'=>1,'codigo'=>'74942','nombre'=>'ACTIVIDADES DE FOTOGRAFIA'],
            ['catalogo_id'=>1,'codigo'=>'74955','nombre'=>'ACTIVIDADES DE ENVASE Y EMPAQUE'],
            ['catalogo_id'=>1,'codigo'=>'74996','nombre'=>'OTRAS ACTIVIDADES EMPRESARIALES NCP.'],
            ['catalogo_id'=>1,'codigo'=>'75113','nombre'=>'ACTIV. ADMINIST. PUBLICA EN GENERAL'],
            ['catalogo_id'=>1,'codigo'=>'75126','nombre'=>'REGULACION DE ACTIVID.ORGANISMOS'],
            ['catalogo_id'=>1,'codigo'=>'75139','nombre'=>'REGULAC. Y FACILITAC. ACTIV.ECONOMIC.'],
            ['catalogo_id'=>1,'codigo'=>'75141','nombre'=>'SERVIC. AUXIL.PARA ADMINIST.PUBLICA.'],
            ['catalogo_id'=>1,'codigo'=>'75214','nombre'=>'RELACIONES EXTERIORES'],
            ['catalogo_id'=>1,'codigo'=>'75227','nombre'=>'ACTIVIDADES DE DEFENSA'],
            ['catalogo_id'=>1,'codigo'=>'75230','nombre'=>'MANTENIMIENTO DEL ORDEN PUBLICO'],
            ['catalogo_id'=>1,'codigo'=>'75302','nombre'=>'SERVICIOS PUBLICOS SEGURIDAD SOCIAL'],
            ['catalogo_id'=>1,'codigo'=>'80107','nombre'=>'ENSEÑANZA PRIMARIA'],
            ['catalogo_id'=>1,'codigo'=>'80210','nombre'=>'ENSEÑANZA SECUNDARIA  FORMACION GRAL.'],
            ['catalogo_id'=>1,'codigo'=>'80223','nombre'=>'ENSEÑANZA SECUNDARIA FORMAC. TECNICA.'],
            ['catalogo_id'=>1,'codigo'=>'80309','nombre'=>'ENSEÑANZA SUPERIOR'],
            ['catalogo_id'=>1,'codigo'=>'80904','nombre'=>'EDUCACION DE ADULTOS Y OTROS'],
            ['catalogo_id'=>1,'codigo'=>'85111','nombre'=>'ACTIVIDADES DE HOSPITALES'],
            ['catalogo_id'=>1,'codigo'=>'85124','nombre'=>'ACTIVIDADES DE MEDICOS Y ODONTOLOGO'],
            ['catalogo_id'=>1,'codigo'=>'85193','nombre'=>'OTRAS ACTIV.RELAC. CON SALUD HUMANA'],
            ['catalogo_id'=>1,'codigo'=>'85200','nombre'=>'ACTIVIDADES VETERINARIAS'],
            ['catalogo_id'=>1,'codigo'=>'85313','nombre'=>'SERVICIOS SOCIALES CON ALOJAMIENTO'],
            ['catalogo_id'=>1,'codigo'=>'85326','nombre'=>'SERVICIOS SOCIALES SIN ALOJAMIENTO'],
            ['catalogo_id'=>1,'codigo'=>'90004','nombre'=>'ELIMINACION DE DESPERDICIOS'],
            ['catalogo_id'=>1,'codigo'=>'91114','nombre'=>'ACTIV.ORGANIZACIONES EMPRESARIALES'],
            ['catalogo_id'=>1,'codigo'=>'91127','nombre'=>'ACTIV.ORGANIZACIONES PROFESIONALES.'],
            ['catalogo_id'=>1,'codigo'=>'91202','nombre'=>'ACTIVIDADES DE SINDICATOS'],
            ['catalogo_id'=>1,'codigo'=>'91911','nombre'=>'ACTIV.ORGANIZACIONES RELIGIOSAS'],
            ['catalogo_id'=>1,'codigo'=>'91924','nombre'=>'ACTIV.ORGANIZACIONES POLITICAS'],
            ['catalogo_id'=>1,'codigo'=>'91993','nombre'=>'ACTIVIDADES OTRAS ASOCIACIONES NCP.'],
            ['catalogo_id'=>1,'codigo'=>'92110','nombre'=>'PRODUCCION Y DIST.FILMES Y VIDEOS'],
            ['catalogo_id'=>1,'codigo'=>'92123','nombre'=>'EXHIBICION FILMES Y VIDEOS'],
            ['catalogo_id'=>1,'codigo'=>'92136','nombre'=>'ACTIVIDADES DE RADIO Y TELEVISION.'],
            ['catalogo_id'=>1,'codigo'=>'92149','nombre'=>'ACTIV.TEATRALES,  MUSICALES Y OTRAS.'],
            ['catalogo_id'=>1,'codigo'=>'92192','nombre'=>'OTRAS ACTIVID.ENTRETENIMIENTO NCP.'],
            ['catalogo_id'=>1,'codigo'=>'92209','nombre'=>'ACTIVIDADES DE AGENCIAS DE NOTICIAS'],
            ['catalogo_id'=>1,'codigo'=>'92312','nombre'=>'ACTIVIDADES BIBLIOTECAS Y ARCHIVOS'],
            ['catalogo_id'=>1,'codigo'=>'92325','nombre'=>'ACTIV.MUSEOS Y LUGARES HISTORICOS.'],
            ['catalogo_id'=>1,'codigo'=>'92338','nombre'=>'ACTIV.JARDINES BOTANICOS Y ZOOLOGIC.'],
            ['catalogo_id'=>1,'codigo'=>'92413','nombre'=>'ACTIVIDADES DEPORTIVAS'],
            ['catalogo_id'=>1,'codigo'=>'92495','nombre'=>'OTRAS ACTIVIDADES DE ESPARCIMIENTO'],
            ['catalogo_id'=>1,'codigo'=>'93016','nombre'=>'LAVADO, LIMPIEZA Y TEÑIDO TELA'],
            ['catalogo_id'=>1,'codigo'=>'93029','nombre'=>'PELUQUERIA Y OTROS'],
            ['catalogo_id'=>1,'codigo'=>'93031','nombre'=>'POMPAS FUNEBRES Y ACTIVID.CONEXAS'],
            ['catalogo_id'=>1,'codigo'=>'93098','nombre'=>'OTRAS ACTIVID.DE TIPO SERVICIO NCP'],
            ['catalogo_id'=>1,'codigo'=>'95006','nombre'=>'HOGARES PRIVADOS C. SERV.DOMESTICO'],
            ['catalogo_id'=>1,'codigo'=>'99001','nombre'=>'ORGANIZACIONES INTERNACIONALES']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>3,'codigo'=>'01','nombre'=>'DOCUMENTO  NACIONAL DE IDENTIDAD','abreviatura'=>'DNI'],
            ['catalogo_id'=>3,'codigo'=>'04','nombre'=>'CARNÉ DE EXTRANJERÍA','abreviatura'=>'CARNÉ EXT.'],
            ['catalogo_id'=>3,'codigo'=>'06','nombre'=>'REG. ÚNICO DE CONTRIBUYENTES (1)','abreviatura'=>'RUC'],
            ['catalogo_id'=>3,'codigo'=>'07','nombre'=>'PASAPORTE','abreviatura'=>'PASAPORTE'],
            ['catalogo_id'=>3,'codigo'=>'09','nombre'=>'CARNÉ DE SOLICIT DE REFUGIO','abreviatura'=>'CARNÉ SOLIC REFUGIO'],
            ['catalogo_id'=>3,'codigo'=>'11','nombre'=>'PARTIDA DE NACIMIENTO (2)','abreviatura'=>'PART. NAC.']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>4,'codigo'=>'9001','nombre'=>'BOUVET ISLAND'],
            ['catalogo_id'=>4,'codigo'=>'9002','nombre'=>'COTE D IVOIRE'],
            ['catalogo_id'=>4,'codigo'=>'9003','nombre'=>'FALKLAND ISLANDS (MALVINAS)'],
            ['catalogo_id'=>4,'codigo'=>'9004','nombre'=>'FRANCE, METROPOLITAN'],
            ['catalogo_id'=>4,'codigo'=>'9005','nombre'=>'FRENCH SOUTHERN TERRITORIES'],
            ['catalogo_id'=>4,'codigo'=>'9006','nombre'=>'HEARD AND MC DONALD ISLANDS'],
            ['catalogo_id'=>4,'codigo'=>'9007','nombre'=>'MAYOTTE'],
            ['catalogo_id'=>4,'codigo'=>'9008','nombre'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'],
            ['catalogo_id'=>4,'codigo'=>'9009','nombre'=>'SVALBARD AND JAN MAYEN ISLANDS'],
            ['catalogo_id'=>4,'codigo'=>'9010','nombre'=>'UNITED STATES MINOR OUTLYING ISLANDS'],
            ['catalogo_id'=>4,'codigo'=>'9011','nombre'=>'OTROS PAISES O LUGARES'],
            ['catalogo_id'=>4,'codigo'=>'9013','nombre'=>'AFGANISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9017','nombre'=>'ALBANIA'],
            ['catalogo_id'=>4,'codigo'=>'9019','nombre'=>'ALDERNEY'],
            ['catalogo_id'=>4,'codigo'=>'9023','nombre'=>'ALEMANIA'],
            ['catalogo_id'=>4,'codigo'=>'9026','nombre'=>'ARMENIA'],
            ['catalogo_id'=>4,'codigo'=>'9027','nombre'=>'ARUBA'],
            ['catalogo_id'=>4,'codigo'=>'9028','nombre'=>'ASCENCION'],
            ['catalogo_id'=>4,'codigo'=>'9029','nombre'=>'BOSNIA-HERZEGOVINA'],
            ['catalogo_id'=>4,'codigo'=>'9031','nombre'=>'BURKINA FASO'],
            ['catalogo_id'=>4,'codigo'=>'9037','nombre'=>'ANDORRA'],
            ['catalogo_id'=>4,'codigo'=>'9040','nombre'=>'ANGOLA'],
            ['catalogo_id'=>4,'codigo'=>'9041','nombre'=>'ANGUILLA'],
            ['catalogo_id'=>4,'codigo'=>'9043','nombre'=>'ANTIGUA Y BARBUDA'],
            ['catalogo_id'=>4,'codigo'=>'9047','nombre'=>'ANTILLAS HOLANDESAS'],
            ['catalogo_id'=>4,'codigo'=>'9053','nombre'=>'ARABIA SAUDITA'],
            ['catalogo_id'=>4,'codigo'=>'9059','nombre'=>'ARGELIA'],
            ['catalogo_id'=>4,'codigo'=>'9063','nombre'=>'ARGENTINA'],
            ['catalogo_id'=>4,'codigo'=>'9069','nombre'=>'AUSTRALIA'],
            ['catalogo_id'=>4,'codigo'=>'9072','nombre'=>'AUSTRIA'],
            ['catalogo_id'=>4,'codigo'=>'9074','nombre'=>'AZERBAIJÁN'],
            ['catalogo_id'=>4,'codigo'=>'9077','nombre'=>'BAHAMAS'],
            ['catalogo_id'=>4,'codigo'=>'9080','nombre'=>'BAHREIN'],
            ['catalogo_id'=>4,'codigo'=>'9081','nombre'=>'BANGLA DESH'],
            ['catalogo_id'=>4,'codigo'=>'9083','nombre'=>'BARBADOS'],
            ['catalogo_id'=>4,'codigo'=>'9087','nombre'=>'BÉLGICA'],
            ['catalogo_id'=>4,'codigo'=>'9088','nombre'=>'BELICE'],
            ['catalogo_id'=>4,'codigo'=>'9090','nombre'=>'BERMUDAS'],
            ['catalogo_id'=>4,'codigo'=>'9091','nombre'=>'BELARUS'],
            ['catalogo_id'=>4,'codigo'=>'9093','nombre'=>'MYANMAR'],
            ['catalogo_id'=>4,'codigo'=>'9097','nombre'=>'BOLIVIA'],
            ['catalogo_id'=>4,'codigo'=>'9101','nombre'=>'BOTSWANA'],
            ['catalogo_id'=>4,'codigo'=>'9105','nombre'=>'BRASIL'],
            ['catalogo_id'=>4,'codigo'=>'9108','nombre'=>'BRUNEI DARUSSALAM'],
            ['catalogo_id'=>4,'codigo'=>'9111','nombre'=>'BULGARIA'],
            ['catalogo_id'=>4,'codigo'=>'9115','nombre'=>'BURUNDI'],
            ['catalogo_id'=>4,'codigo'=>'9119','nombre'=>'BUTÁN'],
            ['catalogo_id'=>4,'codigo'=>'9127','nombre'=>'CABO VERDE'],
            ['catalogo_id'=>4,'codigo'=>'9137','nombre'=>'CAIMÁN, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9141','nombre'=>'CAMBOYA'],
            ['catalogo_id'=>4,'codigo'=>'9145','nombre'=>'CAMERÚN, REPUBLICA UNIDA DEL'],
            ['catalogo_id'=>4,'codigo'=>'9147','nombre'=>'CAMPIONE D TALIA'],
            ['catalogo_id'=>4,'codigo'=>'9149','nombre'=>'CANADÁ'],
            ['catalogo_id'=>4,'codigo'=>'9155','nombre'=>'CANAL (NORMANDAS), ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9157','nombre'=>'CANTÓN Y ENDERBURRY'],
            ['catalogo_id'=>4,'codigo'=>'9159','nombre'=>'SANTA SEDE'],
            ['catalogo_id'=>4,'codigo'=>'9165','nombre'=>'COCOS (KEELING),ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9169','nombre'=>'COLOMBIA'],
            ['catalogo_id'=>4,'codigo'=>'9173','nombre'=>'COMORAS'],
            ['catalogo_id'=>4,'codigo'=>'9177','nombre'=>'CONGO'],
            ['catalogo_id'=>4,'codigo'=>'9183','nombre'=>'COOK, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9187','nombre'=>'COREA (NORTE), REPUBLICA POPULAR DEMOCRATICA DE'],
            ['catalogo_id'=>4,'codigo'=>'9190','nombre'=>'COREA (SUR), REPUBLICA DE'],
            ['catalogo_id'=>4,'codigo'=>'9193','nombre'=>'COSTA DE MARFIL'],
            ['catalogo_id'=>4,'codigo'=>'9196','nombre'=>'COSTA RICA'],
            ['catalogo_id'=>4,'codigo'=>'9198','nombre'=>'CROACIA'],
            ['catalogo_id'=>4,'codigo'=>'9199','nombre'=>'CUBA'],
            ['catalogo_id'=>4,'codigo'=>'9203','nombre'=>'CHAD'],
            ['catalogo_id'=>4,'codigo'=>'9207','nombre'=>'CHECOSLOVAQUIA'],
            ['catalogo_id'=>4,'codigo'=>'9211','nombre'=>'CHILE'],
            ['catalogo_id'=>4,'codigo'=>'9215','nombre'=>'CHINA'],
            ['catalogo_id'=>4,'codigo'=>'9218','nombre'=>'TAIWAN (FORMOSA)'],
            ['catalogo_id'=>4,'codigo'=>'9221','nombre'=>'CHIPRE'],
            ['catalogo_id'=>4,'codigo'=>'9229','nombre'=>'BENIN'],
            ['catalogo_id'=>4,'codigo'=>'9232','nombre'=>'DINAMARCA'],
            ['catalogo_id'=>4,'codigo'=>'9235','nombre'=>'DOMINICA'],
            ['catalogo_id'=>4,'codigo'=>'9239','nombre'=>'ECUADOR'],
            ['catalogo_id'=>4,'codigo'=>'9240','nombre'=>'EGIPTO'],
            ['catalogo_id'=>4,'codigo'=>'9242','nombre'=>'EL SALVADOR'],
            ['catalogo_id'=>4,'codigo'=>'9243','nombre'=>'ERITREA'],
            ['catalogo_id'=>4,'codigo'=>'9244','nombre'=>'EMIRATOS ARABES UNIDOS'],
            ['catalogo_id'=>4,'codigo'=>'9245','nombre'=>'ESPAÑA'],
            ['catalogo_id'=>4,'codigo'=>'9246','nombre'=>'ESLOVAQUIA'],
            ['catalogo_id'=>4,'codigo'=>'9247','nombre'=>'ESLOVENIA'],
            ['catalogo_id'=>4,'codigo'=>'9249','nombre'=>'ESTADOS UNIDOS'],
            ['catalogo_id'=>4,'codigo'=>'9251','nombre'=>'ESTONIA'],
            ['catalogo_id'=>4,'codigo'=>'9253','nombre'=>'ETIOPIA'],
            ['catalogo_id'=>4,'codigo'=>'9259','nombre'=>'FEROE, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9267','nombre'=>'FILIPINAS'],
            ['catalogo_id'=>4,'codigo'=>'9271','nombre'=>'FINLANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9275','nombre'=>'FRANCIA'],
            ['catalogo_id'=>4,'codigo'=>'9281','nombre'=>'GABON'],
            ['catalogo_id'=>4,'codigo'=>'9285','nombre'=>'GAMBIA'],
            ['catalogo_id'=>4,'codigo'=>'9286','nombre'=>'GAZA Y JERICO'],
            ['catalogo_id'=>4,'codigo'=>'9287','nombre'=>'GEORGIA'],
            ['catalogo_id'=>4,'codigo'=>'9289','nombre'=>'GHANA'],
            ['catalogo_id'=>4,'codigo'=>'9293','nombre'=>'GIBRALTAR'],
            ['catalogo_id'=>4,'codigo'=>'9297','nombre'=>'GRANADA'],
            ['catalogo_id'=>4,'codigo'=>'9301','nombre'=>'GRECIA'],
            ['catalogo_id'=>4,'codigo'=>'9305','nombre'=>'GROENLANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9309','nombre'=>'GUADALUPE'],
            ['catalogo_id'=>4,'codigo'=>'9313','nombre'=>'GUAM'],
            ['catalogo_id'=>4,'codigo'=>'9317','nombre'=>'GUATEMALA'],
            ['catalogo_id'=>4,'codigo'=>'9325','nombre'=>'GUAYANA FRANCESA'],
            ['catalogo_id'=>4,'codigo'=>'9327','nombre'=>'GUERNSEY'],
            ['catalogo_id'=>4,'codigo'=>'9329','nombre'=>'GUINEA'],
            ['catalogo_id'=>4,'codigo'=>'9331','nombre'=>'GUINEA ECUATORIAL'],
            ['catalogo_id'=>4,'codigo'=>'9334','nombre'=>'GUINEA-BISSAU'],
            ['catalogo_id'=>4,'codigo'=>'9337','nombre'=>'GUYANA'],
            ['catalogo_id'=>4,'codigo'=>'9341','nombre'=>'HAITI'],
            ['catalogo_id'=>4,'codigo'=>'9345','nombre'=>'HONDURAS'],
            ['catalogo_id'=>4,'codigo'=>'9348','nombre'=>'HONDURAS BRITANICAS'],
            ['catalogo_id'=>4,'codigo'=>'9351','nombre'=>'HONG KONG'],
            ['catalogo_id'=>4,'codigo'=>'9355','nombre'=>'HUNGRIA'],
            ['catalogo_id'=>4,'codigo'=>'9361','nombre'=>'INDIA'],
            ['catalogo_id'=>4,'codigo'=>'9365','nombre'=>'INDONESIA'],
            ['catalogo_id'=>4,'codigo'=>'9369','nombre'=>'IRAK'],
            ['catalogo_id'=>4,'codigo'=>'9372','nombre'=>'IRAN, REPUBLICA ISLAMICA DEL'],
            ['catalogo_id'=>4,'codigo'=>'9375','nombre'=>'IRLANDA (EIRE)'],
            ['catalogo_id'=>4,'codigo'=>'9377','nombre'=>'ISLA AZORES'],
            ['catalogo_id'=>4,'codigo'=>'9378','nombre'=>'ISLA DEL MAN'],
            ['catalogo_id'=>4,'codigo'=>'9379','nombre'=>'ISLANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9380','nombre'=>'ISLAS CANARIAS'],
            ['catalogo_id'=>4,'codigo'=>'9381','nombre'=>'ISLAS DE CHRISTMAS'],
            ['catalogo_id'=>4,'codigo'=>'9382','nombre'=>'ISLAS QESHM'],
            ['catalogo_id'=>4,'codigo'=>'9383','nombre'=>'ISRAEL'],
            ['catalogo_id'=>4,'codigo'=>'9386','nombre'=>'ITALIA'],
            ['catalogo_id'=>4,'codigo'=>'9391','nombre'=>'JAMAICA'],
            ['catalogo_id'=>4,'codigo'=>'9395','nombre'=>'JONSTON, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9399','nombre'=>'JAPON'],
            ['catalogo_id'=>4,'codigo'=>'9401','nombre'=>'JERSEY'],
            ['catalogo_id'=>4,'codigo'=>'9403','nombre'=>'JORDANIA'],
            ['catalogo_id'=>4,'codigo'=>'9406','nombre'=>'KAZAJSTAN'],
            ['catalogo_id'=>4,'codigo'=>'9410','nombre'=>'KENIA'],
            ['catalogo_id'=>4,'codigo'=>'9411','nombre'=>'KIRIBATI'],
            ['catalogo_id'=>4,'codigo'=>'9412','nombre'=>'KIRGUIZISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9413','nombre'=>'KUWAIT'],
            ['catalogo_id'=>4,'codigo'=>'9418','nombre'=>'LABUN'],
            ['catalogo_id'=>4,'codigo'=>'9420','nombre'=>'LAOS, REPUBLICA POPULAR DEMOCRATICA DE'],
            ['catalogo_id'=>4,'codigo'=>'9426','nombre'=>'LESOTHO'],
            ['catalogo_id'=>4,'codigo'=>'9429','nombre'=>'LETONIA'],
            ['catalogo_id'=>4,'codigo'=>'9431','nombre'=>'LIBANO'],
            ['catalogo_id'=>4,'codigo'=>'9434','nombre'=>'LIBERIA'],
            ['catalogo_id'=>4,'codigo'=>'9438','nombre'=>'LIBIA'],
            ['catalogo_id'=>4,'codigo'=>'9440','nombre'=>'LIECHTENSTEIN'],
            ['catalogo_id'=>4,'codigo'=>'9443','nombre'=>'LITUANIA'],
            ['catalogo_id'=>4,'codigo'=>'9445','nombre'=>'LUXEMBURGO'],
            ['catalogo_id'=>4,'codigo'=>'9447','nombre'=>'MACAO'],
            ['catalogo_id'=>4,'codigo'=>'9448','nombre'=>'MACEDONIA'],
            ['catalogo_id'=>4,'codigo'=>'9450','nombre'=>'MADAGASCAR'],
            ['catalogo_id'=>4,'codigo'=>'9453','nombre'=>'MADEIRA'],
            ['catalogo_id'=>4,'codigo'=>'9455','nombre'=>'MALAYSIA'],
            ['catalogo_id'=>4,'codigo'=>'9458','nombre'=>'MALAWI'],
            ['catalogo_id'=>4,'codigo'=>'9461','nombre'=>'MALDIVAS'],
            ['catalogo_id'=>4,'codigo'=>'9464','nombre'=>'MALI'],
            ['catalogo_id'=>4,'codigo'=>'9467','nombre'=>'MALTA'],
            ['catalogo_id'=>4,'codigo'=>'9469','nombre'=>'MARIANAS DEL NORTE, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9472','nombre'=>'MARSHALL, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9474','nombre'=>'MARRUECOS'],
            ['catalogo_id'=>4,'codigo'=>'9477','nombre'=>'MARTINICA'],
            ['catalogo_id'=>4,'codigo'=>'9485','nombre'=>'MAURICIO'],
            ['catalogo_id'=>4,'codigo'=>'9488','nombre'=>'MAURITANIA'],
            ['catalogo_id'=>4,'codigo'=>'9493','nombre'=>'MEXICO'],
            ['catalogo_id'=>4,'codigo'=>'9494','nombre'=>'MICRONESIA, ESTADOS FEDERADOS DE'],
            ['catalogo_id'=>4,'codigo'=>'9495','nombre'=>'MIDWAY ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9496','nombre'=>'MOLDAVIA'],
            ['catalogo_id'=>4,'codigo'=>'9497','nombre'=>'MONGOLIA'],
            ['catalogo_id'=>4,'codigo'=>'9498','nombre'=>'MONACO'],
            ['catalogo_id'=>4,'codigo'=>'9501','nombre'=>'MONTSERRAT, ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9505','nombre'=>'MOZAMBIQUE'],
            ['catalogo_id'=>4,'codigo'=>'9507','nombre'=>'NAMIBIA'],
            ['catalogo_id'=>4,'codigo'=>'9508','nombre'=>'NAURU'],
            ['catalogo_id'=>4,'codigo'=>'9511','nombre'=>'NAVIDAD (CHRISTMAS), ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9517','nombre'=>'NEPAL'],
            ['catalogo_id'=>4,'codigo'=>'9521','nombre'=>'NICARAGUA'],
            ['catalogo_id'=>4,'codigo'=>'9525','nombre'=>'NIGER'],
            ['catalogo_id'=>4,'codigo'=>'9528','nombre'=>'NIGERIA'],
            ['catalogo_id'=>4,'codigo'=>'9531','nombre'=>'NIUE, ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9535','nombre'=>'NORFOLK, ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9538','nombre'=>'NORUEGA'],
            ['catalogo_id'=>4,'codigo'=>'9542','nombre'=>'NUEVA CALEDONIA'],
            ['catalogo_id'=>4,'codigo'=>'9545','nombre'=>'PAPUASIA NUEVA GUINEA'],
            ['catalogo_id'=>4,'codigo'=>'9548','nombre'=>'NUEVA ZELANDA'],
            ['catalogo_id'=>4,'codigo'=>'9551','nombre'=>'VANUATU'],
            ['catalogo_id'=>4,'codigo'=>'9556','nombre'=>'OMAN'],
            ['catalogo_id'=>4,'codigo'=>'9566','nombre'=>'PACIFICO, ISLAS DEL'],
            ['catalogo_id'=>4,'codigo'=>'9573','nombre'=>'PAISES BAJOS'],
            ['catalogo_id'=>4,'codigo'=>'9576','nombre'=>'PAKISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9578','nombre'=>'PALAU, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9579','nombre'=>'TERRITORIO AUTONOMO DE PALESTINA.'],
            ['catalogo_id'=>4,'codigo'=>'9580','nombre'=>'PANAMA'],
            ['catalogo_id'=>4,'codigo'=>'9586','nombre'=>'PARAGUAY'],
            ['catalogo_id'=>4,'codigo'=>'9589','nombre'=>'PERÚ'],
            ['catalogo_id'=>4,'codigo'=>'9593','nombre'=>'PITCAIRN, ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9599','nombre'=>'POLINESIA FRANCESA'],
            ['catalogo_id'=>4,'codigo'=>'9603','nombre'=>'POLONIA'],
            ['catalogo_id'=>4,'codigo'=>'9607','nombre'=>'PORTUGAL'],
            ['catalogo_id'=>4,'codigo'=>'9611','nombre'=>'PUERTO RICO'],
            ['catalogo_id'=>4,'codigo'=>'9618','nombre'=>'QATAR'],
            ['catalogo_id'=>4,'codigo'=>'9628','nombre'=>'REINO UNIDO'],
            ['catalogo_id'=>4,'codigo'=>'9629','nombre'=>'ESCOCIA'],
            ['catalogo_id'=>4,'codigo'=>'9633','nombre'=>'REPUBLICA ARABE UNIDA'],
            ['catalogo_id'=>4,'codigo'=>'9640','nombre'=>'REPUBLICA CENTROAFRICANA'],
            ['catalogo_id'=>4,'codigo'=>'9644','nombre'=>'REPUBLICA CHECA'],
            ['catalogo_id'=>4,'codigo'=>'9645','nombre'=>'REPUBLICA DE SWAZILANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9646','nombre'=>'REPUBLICA DE TUNEZ'],
            ['catalogo_id'=>4,'codigo'=>'9647','nombre'=>'REPUBLICA DOMINICANA'],
            ['catalogo_id'=>4,'codigo'=>'9660','nombre'=>'REUNION'],
            ['catalogo_id'=>4,'codigo'=>'9665','nombre'=>'ZIMBABWE'],
            ['catalogo_id'=>4,'codigo'=>'9670','nombre'=>'RUMANIA'],
            ['catalogo_id'=>4,'codigo'=>'9675','nombre'=>'RUANDA'],
            ['catalogo_id'=>4,'codigo'=>'9676','nombre'=>'RUSIA'],
            ['catalogo_id'=>4,'codigo'=>'9677','nombre'=>'SALOMON, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9685','nombre'=>'SAHARA OCCIDENTAL'],
            ['catalogo_id'=>4,'codigo'=>'9687','nombre'=>'SAMOA OCCIDENTAL'],
            ['catalogo_id'=>4,'codigo'=>'9690','nombre'=>'SAMOA NORTEAMERICANA'],
            ['catalogo_id'=>4,'codigo'=>'9695','nombre'=>'SAN CRISTOBAL Y NIEVES'],
            ['catalogo_id'=>4,'codigo'=>'9697','nombre'=>'SAN MARINO'],
            ['catalogo_id'=>4,'codigo'=>'9700','nombre'=>'SAN PEDRO Y MIQUELON'],
            ['catalogo_id'=>4,'codigo'=>'9705','nombre'=>'SAN VICENTE Y LAS GRANADINAS'],
            ['catalogo_id'=>4,'codigo'=>'9710','nombre'=>'SANTA ELENA'],
            ['catalogo_id'=>4,'codigo'=>'9715','nombre'=>'SANTA LUCIA'],
            ['catalogo_id'=>4,'codigo'=>'9720','nombre'=>'SANTO TOME Y PRINCIPE'],
            ['catalogo_id'=>4,'codigo'=>'9728','nombre'=>'SENEGAL'],
            ['catalogo_id'=>4,'codigo'=>'9731','nombre'=>'SEYCHELLES'],
            ['catalogo_id'=>4,'codigo'=>'9735','nombre'=>'SIERRA LEONA'],
            ['catalogo_id'=>4,'codigo'=>'9741','nombre'=>'SINGAPUR'],
            ['catalogo_id'=>4,'codigo'=>'9744','nombre'=>'SIRIA, REPUBLICA ARABE DE'],
            ['catalogo_id'=>4,'codigo'=>'9748','nombre'=>'SOMALIA'],
            ['catalogo_id'=>4,'codigo'=>'9750','nombre'=>'SRI LANKA'],
            ['catalogo_id'=>4,'codigo'=>'9756','nombre'=>'SUDAFRICA, REPUBLICA DE'],
            ['catalogo_id'=>4,'codigo'=>'9759','nombre'=>'SUDAN'],
            ['catalogo_id'=>4,'codigo'=>'9764','nombre'=>'SUECIA'],
            ['catalogo_id'=>4,'codigo'=>'9767','nombre'=>'SUIZA'],
            ['catalogo_id'=>4,'codigo'=>'9770','nombre'=>'SURINAM'],
            ['catalogo_id'=>4,'codigo'=>'9773','nombre'=>'SAWSILANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9774','nombre'=>'TADJIKISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9776','nombre'=>'TAILANDIA'],
            ['catalogo_id'=>4,'codigo'=>'9780','nombre'=>'TANZANIA, REPUBLICA UNIDA DE'],
            ['catalogo_id'=>4,'codigo'=>'9783','nombre'=>'DJIBOUTI'],
            ['catalogo_id'=>4,'codigo'=>'9786','nombre'=>'TERRITORIO ANTARTICO BRITANICO'],
            ['catalogo_id'=>4,'codigo'=>'9787','nombre'=>'TERRITORIO BRITANICO DEL OCEANO INDICO'],
            ['catalogo_id'=>4,'codigo'=>'9788','nombre'=>'TIMOR DEL ESTE'],
            ['catalogo_id'=>4,'codigo'=>'9800','nombre'=>'TOGO'],
            ['catalogo_id'=>4,'codigo'=>'9805','nombre'=>'TOKELAU'],
            ['catalogo_id'=>4,'codigo'=>'9810','nombre'=>'TONGA'],
            ['catalogo_id'=>4,'codigo'=>'9815','nombre'=>'TRINIDAD Y TOBAGO'],
            ['catalogo_id'=>4,'codigo'=>'9816','nombre'=>'TRISTAN DA CUNHA'],
            ['catalogo_id'=>4,'codigo'=>'9820','nombre'=>'TUNICIA'],
            ['catalogo_id'=>4,'codigo'=>'9823','nombre'=>'TURCAS Y CAICOS, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9825','nombre'=>'TURKMENISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9827','nombre'=>'TURQUIA'],
            ['catalogo_id'=>4,'codigo'=>'9828','nombre'=>'TUVALU'],
            ['catalogo_id'=>4,'codigo'=>'9830','nombre'=>'UCRANIA'],
            ['catalogo_id'=>4,'codigo'=>'9833','nombre'=>'UGANDA'],
            ['catalogo_id'=>4,'codigo'=>'9840','nombre'=>'URSS'],
            ['catalogo_id'=>4,'codigo'=>'9845','nombre'=>'URUGUAY'],
            ['catalogo_id'=>4,'codigo'=>'9847','nombre'=>'UZBEKISTAN'],
            ['catalogo_id'=>4,'codigo'=>'9850','nombre'=>'VENEZUELA'],
            ['catalogo_id'=>4,'codigo'=>'9855','nombre'=>'VIET NAM'],
            ['catalogo_id'=>4,'codigo'=>'9858','nombre'=>'VIETNAM (DEL NORTE)'],
            ['catalogo_id'=>4,'codigo'=>'9863','nombre'=>'VIRGENES, ISLAS (BRITANICAS)'],
            ['catalogo_id'=>4,'codigo'=>'9866','nombre'=>'VIRGENES, ISLAS (NORTEAMERICANAS)'],
            ['catalogo_id'=>4,'codigo'=>'9870','nombre'=>'FIJI'],
            ['catalogo_id'=>4,'codigo'=>'9873','nombre'=>'WAKE, ISLA'],
            ['catalogo_id'=>4,'codigo'=>'9875','nombre'=>'WALLIS Y FORTUNA, ISLAS'],
            ['catalogo_id'=>4,'codigo'=>'9880','nombre'=>'YEMEN'],
            ['catalogo_id'=>4,'codigo'=>'9885','nombre'=>'YUGOSLAVIA'],
            ['catalogo_id'=>4,'codigo'=>'9888','nombre'=>'ZAIRE'],
            ['catalogo_id'=>4,'codigo'=>'9890','nombre'=>'ZAMBIA'],
            ['catalogo_id'=>4,'codigo'=>'9895','nombre'=>'ZONA DEL CANAL DE PANAMA'],
            ['catalogo_id'=>4,'codigo'=>'9896','nombre'=>'ZONA LIBRE OSTRAVA'],
            ['catalogo_id'=>4,'codigo'=>'9897','nombre'=>'ZONA NEUTRAL (PALESTINA)']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>5,'codigo'=>'01','nombre'=>'AVENIDA'],
            ['catalogo_id'=>5,'codigo'=>'02','nombre'=>'JIRÓN'],
            ['catalogo_id'=>5,'codigo'=>'03','nombre'=>'CALLE'],
            ['catalogo_id'=>5,'codigo'=>'04','nombre'=>'PASAJE'],
            ['catalogo_id'=>5,'codigo'=>'05','nombre'=>'ALAMEDA'],
            ['catalogo_id'=>5,'codigo'=>'06','nombre'=>'MALECÓN'],
            ['catalogo_id'=>5,'codigo'=>'07','nombre'=>'OVALO'],
            ['catalogo_id'=>5,'codigo'=>'08','nombre'=>'PARQUE'],
            ['catalogo_id'=>5,'codigo'=>'09','nombre'=>'PLAZA'],
            ['catalogo_id'=>5,'codigo'=>'10','nombre'=>'CARRETERA'],
            ['catalogo_id'=>5,'codigo'=>'13','nombre'=>'TROCHA '],
            ['catalogo_id'=>5,'codigo'=>'14','nombre'=>'CAMINO RURAL'],
            ['catalogo_id'=>5,'codigo'=>'15','nombre'=>'BAJADA'],
            ['catalogo_id'=>5,'codigo'=>'16','nombre'=>'GALERIA '],
            ['catalogo_id'=>5,'codigo'=>'17','nombre'=>'PROLONGACIÓN '],
            ['catalogo_id'=>5,'codigo'=>'18','nombre'=>'PASEO'],
            ['catalogo_id'=>5,'codigo'=>'19','nombre'=>'PLAZUELA'],
            ['catalogo_id'=>5,'codigo'=>'20','nombre'=>'PORTAL'],
            ['catalogo_id'=>5,'codigo'=>'21','nombre'=>'CAMINO AFIRMADO'],
            ['catalogo_id'=>5,'codigo'=>'22','nombre'=>'TROCHA CARROZABLE'],
            ['catalogo_id'=>5,'codigo'=>'99','nombre'=>'OTROS']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>6,'codigo'=>'01','nombre'=>'URB. URBANIZACIÓN'],
            ['catalogo_id'=>6,'codigo'=>'02','nombre'=>'P.J. PUEBLO JOVEN'],
            ['catalogo_id'=>6,'codigo'=>'03','nombre'=>'U.V. UNIDAD VECINAL'],
            ['catalogo_id'=>6,'codigo'=>'04','nombre'=>'C.H. CONJUNTO HABITACIONAL'],
            ['catalogo_id'=>6,'codigo'=>'5','nombre'=>'A.H. ASENTAMIENTO HUMANO'],
            ['catalogo_id'=>6,'codigo'=>'06','nombre'=>'COO. COOPERATIVA'],
            ['catalogo_id'=>6,'codigo'=>'07','nombre'=>'RES. RESIDENCIAL'],
            ['catalogo_id'=>6,'codigo'=>'08','nombre'=>'Z.I. ZONA INDUSTRIAL'],
            ['catalogo_id'=>6,'codigo'=>'09','nombre'=>'GRU. GRUPO'],
            ['catalogo_id'=>6,'codigo'=>'10','nombre'=>'CAS. CASERÍO'],
            ['catalogo_id'=>6,'codigo'=>'11','nombre'=>'FND. FUNDO'],
            ['catalogo_id'=>6,'codigo'=>'99','nombre'=>'OTROS']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>9,'codigo'=>'01','nombre'=>'SIN EDUCACIÓN FORMAL','abreviatura'=>'SIN EDUCACIÓN FORMAL'],
            ['catalogo_id'=>9,'codigo'=>'02','nombre'=>'EDUCACIÓN ESPECIAL INCOMPLETA','abreviatura'=>'ESPECIAL INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'03','nombre'=>'EDUCACIÓN ESPECIAL COMPLETA','abreviatura'=>'ESPECIAL COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'04','nombre'=>'EDUCACIÓN PRIMARIA INCOMPLETA','abreviatura'=>'PRIMARIA INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'05','nombre'=>'EDUCACIÓN PRIMARIA COMPLETA','abreviatura'=>'PRIMARIA COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'06','nombre'=>'EDUCACIÓN SECUNDARIA INCOMPLETA','abreviatura'=>'SECUNDARIA INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'07','nombre'=>'EDUCACIÓN SECUNDARIA COMPLETA','abreviatura'=>'SECUNDARIA COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'08','nombre'=>'EDUCACIÓN TÉCNICA INCOMPLETA (2)','abreviatura'=>'TÉCNICA INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'09','nombre'=>'EDUCACIÓN TÉCNICA COMPLETA (2)','abreviatura'=>'TÉCNICA COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'10','nombre'=>'EDUCACIÓN SUPERIOR (INSTITUTO SUPERIOR, ETC) INCOMPLETA (3)','abreviatura'=>'SUPERIOR INCOMPLETA (INSTIT. SUPER)'],
            ['catalogo_id'=>9,'codigo'=>'11','nombre'=>'EDUCACIÓN SUPERIOR (INSTITUTO SUPERIOR, ETC) COMPLETA  (3)','abreviatura'=>'SUPERIOR COMPLETA  (INSTIT SUPER)'],
            ['catalogo_id'=>9,'codigo'=>'12','nombre'=>'EDUCACIÓN UNIVERSITARIA INCOMPLETA  (4)','abreviatura'=>'UNIVERSITARIA INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'13','nombre'=>'EDUCACIÓN UNIVERSITARIA COMPLETA (4)','abreviatura'=>'UNIVERSITARIA COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'14','nombre'=>'GRADO DE BACHILLER','abreviatura'=>'GRADO DE BACHILLER'],
            ['catalogo_id'=>9,'codigo'=>'15','nombre'=>'TITULADO','abreviatura'=>'TITULADO'],
            ['catalogo_id'=>9,'codigo'=>'16','nombre'=>'ESTUDIOS DE MAESTRÍA INCOMPLETA','abreviatura'=>'ESTUD. MAESTRÍA INCOMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'17','nombre'=>'ESTUDIOS DE MAESTRÍA COMPLETA','abreviatura'=>'ESTUD. MAESTRÍA COMPLETA'],
            ['catalogo_id'=>9,'codigo'=>'18','nombre'=>'GRADO DE MAESTRÍA','abreviatura'=>'GRADO DE MAESTRÍA'],
            ['catalogo_id'=>9,'codigo'=>'19','nombre'=>'ESTUDIOS DE DOCTORADO INCOMPLETO','abreviatura'=>'ESTUD. DOCTORADO INCOMPLETO'],
            ['catalogo_id'=>9,'codigo'=>'20','nombre'=>'ESTUDIOS DE DOCTORADO COMPLETO','abreviatura'=>'ESTUD. DOCTORADO COMPLETO'],
            ['catalogo_id'=>9,'codigo'=>'21','nombre'=>'GRADO DE DOCTOR','abreviatura'=>'GRADO DE DOCTOR']
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>13,'codigo'=>'1','nombre'=>'MENSUAL'],
            ['catalogo_id'=>13,'codigo'=>'2','nombre'=>'QUINCENAL'],
            ['catalogo_id'=>13,'codigo'=>'3','nombre'=>'SEMANAL'],
            ['catalogo_id'=>13,'codigo'=>'4','nombre'=>'DIARIA'],
            ['catalogo_id'=>13,'codigo'=>'5','nombre'=>'OTROS'],
        ]);

        DB::table('det_catalogo')->insert([
            ['catalogo_id'=>15,'codigo'=>'0','nombre'=>'BAJA (1)','abreviatura'=>'BAJA'],
            ['catalogo_id'=>15,'codigo'=>'1','nombre'=>'ACTIVO O SUBSIDIADO (1)','abreviatura'=>'ACTIVO O SUBSIDIADO'],
            ['catalogo_id'=>15,'codigo'=>'2','nombre'=>'SIN VÍNCULO LABORAL CON CONCEPTOS PENDIENTE DE LIQUIDAR  (2)','abreviatura'=>'SIN VINC. LAB. CON CONC PEND POR LIQUIDAR'],
            ['catalogo_id'=>15,'codigo'=>'3','nombre'=>'SUSPENSIÓN PERFECTA DE LABORES (3)','abreviatura'=>'SUSPENSIÓN PERFECTA DE LABORES']
        ]);

        DB::table('det_catalogo')->insert([

        ]);
        DB::table('det_catalogo')->insert([

        ]);
        DB::table('det_catalogo')->insert([

        ]);
        DB::table('det_catalogo')->insert([

        ]);

    }
}
